services:
    # image project
    react-app:
        build:
            context: ./app
        restart: unless-stopped
        command: sh -c "npm install && npm run dev"
        container_name: truco2-client-app-staging
        volumes:
            - ./app:/app/
        networks:
            - appnet
        ports:
            - "4400:4200"
    nginx:
        restart: unless-stopped
        container_name: truco2-client-nginx-staging
        build:
            context: ./nginx
        ports:
            - "8217:80"
        networks:
            - appnet
        depends_on:
            - react-app

networks:
    appnet:
        driver: bridge