version: "3.9"

services:
    # image project
    react-app:
        build:
            context: ./app
        restart: unless-stopped
        # command: sh -c "npm install && npm run build && npm run serve:ssr:smart-menu"
        command: sh -c "npm install && npm run dev"
        container_name: truco2-react-app
        volumes:
            - ./app:/app/
        networks:
            - appnet
        ports:
            - "4200:4200"
    nginx:
        restart: unless-stopped
        build:
            context: ./nginx
        ports:
            - "8017:80"
        networks:
            - appnet
        depends_on:
            - react-app

networks:
    appnet:
        driver: bridge