services:
    # image project
    react-app:
        build:
            context: ./app
        restart: unless-stopped
        command: sh -c "npm ci && npm run build:development && npm run server"
        container_name: truco2-client-app-devel
        volumes:
            - ./app:/app/
        networks:
            - appnet
    nginx:
        restart: unless-stopped
        container_name: truco2-client-nginx-devel
        build:
            context: ./nginx
        ports:
            - "8117:80"
        networks:
            - appnet
        depends_on:
            - react-app

networks:
    appnet:
        driver: bridge